source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'DACircularProgress', '~> 2.3.1'
pod 'pop', '~> 1.0.7'
pod 'SDWebImage', '~> 3.7.2'

end
